"""add person fields per PRD

Revision ID: 39be0dfc7e1d
Revises: e5d8200343c6
Create Date: 2025-11-28 09:14:44.017479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39be0dfc7e1d'
down_revision = 'e5d8200343c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'parent_type',
               existing_type=postgresql.ENUM('list_item', 'list', 'occasion', 'person', name='commentparenttype'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index(op.f('idx_comments_author_id'), table_name='comments')
    op.drop_index(op.f('idx_comments_parent_type_parent_id'), table_name='comments')
    op.create_index(op.f('ix_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.create_index('ix_comments_parent_type_parent_id', 'comments', ['parent_type', 'parent_id'], unique=False)
    op.create_table_comment(
        'comments',
        'Comments on various entities (polymorphic parent relationship)',
        existing_comment=None,
        schema=None
    )
    op.alter_column('gifts', 'extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_list_items_assigned_to'), table_name='list_items')
    op.drop_index(op.f('idx_list_items_gift_id'), table_name='list_items')
    op.drop_index(op.f('idx_list_items_list_id'), table_name='list_items')
    op.drop_index(op.f('idx_list_items_list_id_status'), table_name='list_items')
    op.drop_index(op.f('idx_list_items_status'), table_name='list_items')
    op.create_index('ix_list_items_assigned_to', 'list_items', ['assigned_to'], unique=False)
    op.create_index('ix_list_items_gift_id', 'list_items', ['gift_id'], unique=False)
    op.create_index('ix_list_items_list_id', 'list_items', ['list_id'], unique=False)
    op.create_index('ix_list_items_list_status', 'list_items', ['list_id', 'status'], unique=False)
    op.create_index('ix_list_items_status', 'list_items', ['status'], unique=False)
    op.create_table_comment(
        'list_items',
        'Junction table linking gifts to lists with status tracking',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('idx_lists_occasion_id'), table_name='lists')
    op.drop_index(op.f('idx_lists_person_id'), table_name='lists')
    op.drop_index(op.f('idx_lists_type'), table_name='lists')
    op.drop_index(op.f('idx_lists_user_id'), table_name='lists')
    op.drop_index(op.f('idx_lists_user_id_type'), table_name='lists')
    op.drop_index(op.f('idx_lists_visibility'), table_name='lists')
    op.create_index('ix_lists_occasion_id', 'lists', ['occasion_id'], unique=False)
    op.create_index('ix_lists_person_id', 'lists', ['person_id'], unique=False)
    op.create_index('ix_lists_type', 'lists', ['type'], unique=False)
    op.create_index('ix_lists_user_id', 'lists', ['user_id'], unique=False)
    op.create_index('ix_lists_user_type', 'lists', ['user_id', 'type'], unique=False)
    op.create_index('ix_lists_visibility', 'lists', ['visibility'], unique=False)
    op.create_index(op.f('ix_occasions_date'), 'occasions', ['date'], unique=False)
    op.create_index(op.f('ix_occasions_type'), 'occasions', ['type'], unique=False)
    op.add_column('persons', sa.Column('display_name', sa.String(length=100), nullable=False))
    op.add_column('persons', sa.Column('relationship', sa.String(length=100), nullable=True))
    op.add_column('persons', sa.Column('birthdate', sa.Date(), nullable=True))
    op.add_column('persons', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('persons', sa.Column('constraints', sa.Text(), nullable=True))
    op.add_column('persons', sa.Column('photo_url', sa.String(length=500), nullable=True))
    op.alter_column('persons', 'interests',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('persons', 'sizes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_persons_name'), table_name='persons')
    op.create_index(op.f('ix_persons_display_name'), 'persons', ['display_name'], unique=False)
    op.drop_column('persons', 'name')
    op.drop_constraint(op.f('tags_name_key'), 'tags', type_='unique')
    op.create_table_comment(
        'users',
        'Family members with authentication credentials',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'users',
        existing_comment='Family members with authentication credentials',
        schema=None
    )
    op.create_unique_constraint(op.f('tags_name_key'), 'tags', ['name'], postgresql_nulls_not_distinct=False)
    op.add_column('persons', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_persons_display_name'), table_name='persons')
    op.create_index(op.f('ix_persons_name'), 'persons', ['name'], unique=False)
    op.alter_column('persons', 'sizes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('persons', 'interests',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('persons', 'photo_url')
    op.drop_column('persons', 'constraints')
    op.drop_column('persons', 'notes')
    op.drop_column('persons', 'birthdate')
    op.drop_column('persons', 'relationship')
    op.drop_column('persons', 'display_name')
    op.drop_index(op.f('ix_occasions_type'), table_name='occasions')
    op.drop_index(op.f('ix_occasions_date'), table_name='occasions')
    op.drop_index('ix_lists_visibility', table_name='lists')
    op.drop_index('ix_lists_user_type', table_name='lists')
    op.drop_index('ix_lists_user_id', table_name='lists')
    op.drop_index('ix_lists_type', table_name='lists')
    op.drop_index('ix_lists_person_id', table_name='lists')
    op.drop_index('ix_lists_occasion_id', table_name='lists')
    op.create_index(op.f('idx_lists_visibility'), 'lists', ['visibility'], unique=False)
    op.create_index(op.f('idx_lists_user_id_type'), 'lists', ['user_id', 'type'], unique=False)
    op.create_index(op.f('idx_lists_user_id'), 'lists', ['user_id'], unique=False)
    op.create_index(op.f('idx_lists_type'), 'lists', ['type'], unique=False)
    op.create_index(op.f('idx_lists_person_id'), 'lists', ['person_id'], unique=False)
    op.create_index(op.f('idx_lists_occasion_id'), 'lists', ['occasion_id'], unique=False)
    op.drop_table_comment(
        'list_items',
        existing_comment='Junction table linking gifts to lists with status tracking',
        schema=None
    )
    op.drop_index('ix_list_items_status', table_name='list_items')
    op.drop_index('ix_list_items_list_status', table_name='list_items')
    op.drop_index('ix_list_items_list_id', table_name='list_items')
    op.drop_index('ix_list_items_gift_id', table_name='list_items')
    op.drop_index('ix_list_items_assigned_to', table_name='list_items')
    op.create_index(op.f('idx_list_items_status'), 'list_items', ['status'], unique=False)
    op.create_index(op.f('idx_list_items_list_id_status'), 'list_items', ['list_id', 'status'], unique=False)
    op.create_index(op.f('idx_list_items_list_id'), 'list_items', ['list_id'], unique=False)
    op.create_index(op.f('idx_list_items_gift_id'), 'list_items', ['gift_id'], unique=False)
    op.create_index(op.f('idx_list_items_assigned_to'), 'list_items', ['assigned_to'], unique=False)
    op.alter_column('gifts', 'extra_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_table_comment(
        'comments',
        existing_comment='Comments on various entities (polymorphic parent relationship)',
        schema=None
    )
    op.drop_index('ix_comments_parent_type_parent_id', table_name='comments')
    op.drop_index(op.f('ix_comments_author_id'), table_name='comments')
    op.create_index(op.f('idx_comments_parent_type_parent_id'), 'comments', ['parent_type', 'parent_id'], unique=False)
    op.create_index(op.f('idx_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.alter_column('comments', 'parent_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('list_item', 'list', 'occasion', 'person', name='commentparenttype'),
               existing_nullable=False)
    # ### end Alembic commands ###
