"""add gift from_santa field

Revision ID: a9a8b7496861
Revises: df8e08cce5fd
Create Date: 2025-12-22 20:56:49.987540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9a8b7496861'
down_revision = 'df8e08cce5fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_actor_entity'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_actor_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_entity_type'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.create_index('idx_comments_author_id', 'comments', ['author_id'], unique=False)
    op.alter_column('field_options', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_gift_people_gift_id'), table_name='gift_people')
    op.drop_index(op.f('ix_gift_people_person_id'), table_name='gift_people')
    op.drop_index(op.f('uq_gift_people_gift_person'), table_name='gift_people')
    op.add_column('gift_stores', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_gift_stores_gift_id'), table_name='gift_stores')
    op.drop_index(op.f('ix_gift_stores_store_id'), table_name='gift_stores')
    op.drop_index(op.f('ix_gift_stores_unique'), table_name='gift_stores')
    op.create_unique_constraint('uq_gift_store', 'gift_stores', ['gift_id', 'store_id'])
    op.add_column('gifts', sa.Column('from_santa', sa.Boolean(), server_default='false', nullable=False))
    op.drop_index(op.f('ix_gifts_priority'), table_name='gifts')
    op.drop_index(op.f('ix_gifts_purchase_date'), table_name='gifts')
    op.drop_constraint(op.f('groups_name_key'), 'groups', type_='unique')
    op.alter_column('occasions', 'recurrence_rule',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_occasions_is_active'), table_name='occasions')
    op.create_index(op.f('ix_occasions_type'), 'occasions', ['type'], unique=False)
    op.add_column('person_groups', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_person_groups_group_id'), table_name='person_groups')
    op.drop_index(op.f('ix_person_groups_person_id'), table_name='person_groups')
    op.drop_index(op.f('uq_person_groups_person_group'), table_name='person_groups')
    op.create_unique_constraint('uq_person_group', 'person_groups', ['person_id', 'group_id'])
    op.add_column('person_occasions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('idx_person_occasions_budget_lookup'), table_name='person_occasions')
    op.drop_index(op.f('idx_person_occasions_occasion_id'), table_name='person_occasions')
    op.drop_index(op.f('idx_person_occasions_person_id'), table_name='person_occasions')
    op.drop_index(op.f('idx_person_occasions_person_occasion'), table_name='person_occasions')
    op.drop_constraint(op.f('uq_person_occasions_person_occasion'), 'person_occasions', type_='unique')
    op.create_unique_constraint('uq_person_occasion', 'person_occasions', ['person_id', 'occasion_id'])
    op.drop_index(op.f('idx_persons_anniversary'), table_name='persons')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_persons_anniversary'), 'persons', ['anniversary'], unique=False)
    op.drop_constraint('uq_person_occasion', 'person_occasions', type_='unique')
    op.create_unique_constraint(op.f('uq_person_occasions_person_occasion'), 'person_occasions', ['person_id', 'occasion_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_person_occasions_person_occasion'), 'person_occasions', ['person_id', 'occasion_id'], unique=True)
    op.create_index(op.f('idx_person_occasions_person_id'), 'person_occasions', ['person_id'], unique=False)
    op.create_index(op.f('idx_person_occasions_occasion_id'), 'person_occasions', ['occasion_id'], unique=False)
    op.create_index(op.f('idx_person_occasions_budget_lookup'), 'person_occasions', ['person_id', 'occasion_id'], unique=False)
    op.drop_column('person_occasions', 'updated_at')
    op.drop_constraint('uq_person_group', 'person_groups', type_='unique')
    op.create_index(op.f('uq_person_groups_person_group'), 'person_groups', ['person_id', 'group_id'], unique=True)
    op.create_index(op.f('ix_person_groups_person_id'), 'person_groups', ['person_id'], unique=False)
    op.create_index(op.f('ix_person_groups_group_id'), 'person_groups', ['group_id'], unique=False)
    op.drop_column('person_groups', 'updated_at')
    op.drop_index(op.f('ix_occasions_type'), table_name='occasions')
    op.create_index(op.f('idx_occasions_is_active'), 'occasions', ['is_active'], unique=False)
    op.alter_column('occasions', 'recurrence_rule',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_unique_constraint(op.f('groups_name_key'), 'groups', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_gifts_purchase_date'), 'gifts', ['purchase_date'], unique=False)
    op.create_index(op.f('ix_gifts_priority'), 'gifts', ['priority'], unique=False)
    op.drop_column('gifts', 'from_santa')
    op.drop_constraint('uq_gift_store', 'gift_stores', type_='unique')
    op.create_index(op.f('ix_gift_stores_unique'), 'gift_stores', ['gift_id', 'store_id'], unique=True)
    op.create_index(op.f('ix_gift_stores_store_id'), 'gift_stores', ['store_id'], unique=False)
    op.create_index(op.f('ix_gift_stores_gift_id'), 'gift_stores', ['gift_id'], unique=False)
    op.drop_column('gift_stores', 'updated_at')
    op.create_index(op.f('uq_gift_people_gift_person'), 'gift_people', ['gift_id', 'person_id'], unique=True)
    op.create_index(op.f('ix_gift_people_person_id'), 'gift_people', ['person_id'], unique=False)
    op.create_index(op.f('ix_gift_people_gift_id'), 'gift_people', ['gift_id'], unique=False)
    op.alter_column('field_options', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('idx_comments_author_id', table_name='comments')
    op.create_table('activity_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Type of action performed'),
    sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='User who performed the action'),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Type of entity affected'),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='ID of the affected entity'),
    sa.Column('entity_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Denormalized entity name for display'),
    sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Additional context (old/new values, etc.)'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('activity_logs_actor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('activity_logs_pkey')),
    comment='Activity log for tracking user actions and displaying recent activity feed'
    )
    op.create_index(op.f('ix_activity_logs_entity_type'), 'activity_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_actor_id'), 'activity_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_actor_entity'), 'activity_logs', ['actor_id', 'entity_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    # ### end Alembic commands ###
